### ISSUE TITLE
Accept fasta files with filename extensions ".fas" and ".fasta", not just ".fa"

### ISSUE THREAD

**Issue by kaldari** [gear-genomics/pearl#18]
When I tried to upload a reference sequence into Pearl, it gave me an error message. I wasn't sure what the problem was at first, but then I figured out it was because the filename extension was ".fas", not ".fa" as the program was expecting. Personally, I've used both ".fas" and ".fasta", but never ".fa".

**Comment by tobiasrausch** [comment]
Accepts now fasta, fa and fas
